# Generated by Django 5.0.2 on 2024-02-24 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowing_service", "0002_alter_borrowing_actual_return_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRequired",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PAID", "Paid")],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PAYMENT", "Payment"), ("FINE", "Fine")],
                        default="PAYMENT",
                        max_length=50,
                    ),
                ),
                ("session_url", models.URLField(max_length=511)),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("money_to_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "borrow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="borrowing_service.borrowing",
                    ),
                ),
            ],
        ),
    ]
